[package]
name = "login-client"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_8"] }
adw = { version = "0.4.1", package = "libadwaita", features = ["v1_2"] }
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
