import { Button, VerticalBox, HorizontalBox, LineEdit} from "std-widgets.slint";

export struct LoginData {
    username: string,
    password: string,
}

export component LoginPanel inherits VerticalBox {
    padding: 20px;

    callback on_login_clicked(LoginData);
    in property <string> error;

    property <string> username;
    property <string> password;
    property <bool> can_login: username != "" && password != "";

    function trigger_on_login_clicked() {
        if (!can_login) {
            return;
        }

        root.on_login_clicked({
            username: root.username,
            password: root.password,
        });
    }

    VerticalBox {
        LineEdit {
            width: 200px;
            placeholder-text: "Username";
            text <=> root.username;
            accepted => { trigger_on_login_clicked() }
        }

        LineEdit {
            width: 200px;
            input-type: InputType.password;
            placeholder-text: "Password";
            text <=> root.password;
            accepted => { trigger_on_login_clicked() }
        }
    }

    if self.error != "": Text {
        text: parent.error;
        color: #E00;
        horizontal-alignment: center;
    }

    HorizontalBox {
        alignment: center;

        Button {
            text: "Login";
            enabled: root.can_login;
            clicked => { trigger_on_login_clicked() }
        }
    }
}