import { Button, VerticalBox, HorizontalBox, LineEdit} from "std-widgets.slint";

export struct LoginData {
    username: string,
    password: string,
}

export component LoginPanel inherits VerticalBox {
    padding: 20px;

    callback on_login_clicked(LoginData);
    in property <string> error;

    property <string> username;
    property <string> password;

    VerticalBox {
        LineEdit {
            width: 200px;
            placeholder-text: "Username";
            text <=> root.username;
        }

        LineEdit {
            width: 200px;
            input-type: InputType.password;
            placeholder-text: "Password";
            text <=> root.password;
        }
    }

    if self.error != "": Text {
        text: parent.error;
        color: #E00;
        horizontal-alignment: center;
    }

    HorizontalBox {
        alignment: center;

        Button {
            text: "Login";
            clicked => {
                root.on_login_clicked({
                    username: root.username,
                    password: root.password,
                });
            }
        }
    }
}