import { LoginPanel, LoginData } from "ui/login_panel.slint";
import { LoadingPanel } from "ui/loading_panel.slint";
import { LaunchingPanel } from "ui/launching_panel.slint";

export component MainWindow inherits Window {
    title: "Login Client";

    callback login_clicked(LoginData);
    in-out property <string> active_panel: "login";
    in property <string> error;

    login_panel := LoginPanel {
        visible: active_panel == "login";
        error: parent.error;
        on_login_clicked(login_data) => {
            parent.login_clicked(login_data);
            parent.active_panel = "loading";
        }
    }

    LoadingPanel {
        visible: active_panel == "loading";
    }
    
    LaunchingPanel {
        visible: active_panel == "launching";
    }
}